### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by TheBdouilleur** [dark-eye/com.darkeye.chatGPT#13]
Super plasmoid, really does the job quick and well, thank you very much !
Perhaps to make it fully keyboard-operable you could add an option to map <Esc> key to exit
I've no idea of how to implement it so its only a suggestion !

**Comment by dark-eye** [comment]
@TheBdouilleur I think you can exit it with the same  short cut  you used to open it  (you  can define a shortcut  in the configuration after  right clicking the widget)

**Comment by TheBdouilleur** [comment]
Yep I saw this since
Works well for me, sorry for opening this anyway
