### ISSUE TITLE
Allow to Set Layout Size for Smaller Laptop Resolution

### ISSUE THREAD

**Issue by semarainc** [dark-eye/com.darkeye.chatGPT#2]
hey,
thank you for your project, it helps me a lot when i'm studying :D

currently i have laptop with resolution 1024x600 and 1366x768,
when using this plasmoid/widget it fill the screen i cant resize it

maybe you cant add dynamic resizing on the widget or at least put some config to able to set the widget layout size

sry for my bad english
thanks for your effort

**Comment by dark-eye** [comment]
@semarainc You should be able to  resize the widget  by  holding Meta (Windows) key  and right  clicking mouse  and  dragging  left-right / up-down.

However  plasma  does  pro vide the  ability  to provide a compact widget  i`ll  try and  get to it in the next  version.

**Comment by semarainc** [comment]
Thank you for telling me that :D
but i think providing the resizing for smaller laptop screen is important because for old netbook, the widget shows out of border makes it hard to resize

**Comment by dark-eye** [comment]
@semarainc Since the last version it should now be alot smaller (any smaller and it will start to hinder unsability)
