### ISSUE TITLE
copy/paste support

### ISSUE THREAD

**Issue by zontafil** [dark-eye/com.darkeye.chatGPT#8]
Hello,
When I try to copy some code from chatgpt, it doesn't get copied in the system clipboard. It would be really handy to have copy/paste support.
I will also try to look into the code one of these days to check if it's possible

**Comment by dark-eye** [comment]
@zontafil It  should  work  in the  latest version (v0.7) if  not  check that  the "Allow  ChatGPT  to  access system  clipboard"  checkbox is checked in the widget  options.

If  you still have issues please let me know....

Thanks,
